# 관리자 권한갖기 
sudo: required
# 언어 선택 
language: generic
# 도커 환경 구성 
services:
  - docker
# 스크립트를 실행할 수 있는 환경 설정(스크립트 실행 전) 
before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t ljb1905/docker-react-app -f Dockerfile.dev .
# 실행할 스크립트(테스트 실행) 
script:
  - docker run -e CI=true ljb1905/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  # Elastic Beanstalk에서 확인 가능
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  # Elastic Beanstalk Bucket 확인
  bucket_name: "elasticbeanstalk-ap-northeast-2-97~~"
  # app과 동일
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY